name: Auto Assign Reviewers and Assignees

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto Assign Action
        uses: kentaro-m/auto-assign-action@v2
        with:
          configuration-path: ".github/auto_assign.yml"
