name: E2E Tests (Maestro) - Android

on:
  workflow_call:

jobs:
  maestro:
    name: Maestro E2E
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release
          path: ./artifacts

      - name: Find APK
        id: apk
        run: |
          APK=$(find ./artifacts -name "*.apk" -type f | head -n 1)

          if [ -z "$APK" ]; then
            echo "No APK found."
            exit 1
          fi

          echo "APK found: $APK"
          echo "path=$APK" >> "$GITHUB_OUTPUT"

      - name: Install Maestro
        uses: valodes/maestro-github-action@v1.0.1
        with:
          version: latest
          # Optional: Set environment variables for Maestro if needed
          # env: |
          #   USERNAME=user@example.com
          #   PASSWORD=123

      - name: Run Maestro E2E
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          target: google_apis
          ram-size: 4096M
          emulator-options: >-
            -no-window
            -no-audio
            -no-boot-anim
            -gpu swiftshader_indirect
          script: |
            adb install -r "${{ steps.apk.outputs.path }}"

            maestro test .maestro/ \
              --include-tags smoke \
              --test-output-dir=./maestro-results

      - name: Upload Maestro results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-e2e-results-${{ github.run_number }}
          path: |
            ./maestro-results
            /tmp/emulator.log
          if-no-files-found: warn
          retention-days: 7
