name: Release

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'Release Tag'
        required: true
        default: 'v1.0.0'

  push:
    branches:
      - release-test

permissions:
  contents: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm run test:unit

  call-eas-build-workflow:
    # This job calls the EAS build workflow to build the Android APK.
    # It will only run if the "setup" job passes all tests and checks.
    name: Call EAS Build Workflow
    needs: setup
    uses: ./.github/workflows/eas-build.yml
    secrets: inherit

  call-local-build-workflow:
    # This job calls the local build workflow to build the Android APK.
    # It will only run if the "setup" job passes all tests and checks, and if the EAS build workflow fails.
    name: Call Local Build Workflow
    needs: [setup, call-eas-build-workflow]
    if: always() && needs.setup.result == 'success' && needs.call-eas-build-workflow.result == 'failure'
    uses: ./.github/workflows/local-build.yml
    secrets: inherit

  publish-release:
    # This job will only run if the one of the build workflows (EAS or local) succeeds.
    # It generates release notes and publishes the release.
    name: Publish Release
    needs: [call-eas-build-workflow, call-local-build-workflow]
    if: always() && (needs.call-eas-build-workflow.result == 'success' || needs.call-local-build-workflow.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release
          path: ./artifacts

      - name: Rename APK for Release
        run: |
          TAG_NAME="${{ github.event.inputs.tag-name || github.ref_name }}"   
          mv ./artifacts/*.apk "./artifacts/alibe-${TAG_NAME}.apk"

      - name: Generate Release Notes
        uses: RedCrafter07/release-notes-action@v1.0.1
        id: notes
        with:
          tag-name: ${{ github.event.inputs.tag-name || github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create & Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag-name || github.ref_name }}
          name: ${{ github.event.inputs.tag-name || github.ref_name }}
          body: ${{ steps.notes.outputs.release-notes }}
          draft: false
          prerelease: false
          files: ./artifacts/*.apk
